import MotorDriver

print("initialising ...")
dT = MotorDriver.MotorDriver()

print("begin test ...")
dT.motorTest()
print("end test ...")

print("begin module test ...")

print("\n forward all...\n")
dT.setDistance(100)
dT.setSpeed(50)
dT.setHeading(0)
dT.setTargetHeading(0)
dT.move()
dT.motorStop()

print("\n left turn all half...\n")
dT.setDistance(100)
dT.setSpeed(50)
dT.setHeading(0)
dT.setTargetHeading(-50)
dT.move()
dT.move()
dT.motorStop()

print("\n right turn all half...\n")
dT.setDistance(100)
dT.setSpeed(50)
dT.setHeading(0)
dT.setTargetHeading(50)
dT.move()
dT.move()
dT.motorStop()

print("\n left turn all half >180 ...\n")
dT.setDistance(100)
dT.setSpeed(50)
dT.setHeading(0)
dT.setTargetHeading(200)
dT.move()
dT.move()
dT.motorStop()

print("\n static turn all...\n")
dT.setDistance(100)
dT.setSpeed(0)
dT.setHeading(0)
dT.setTargetHeading(180)
dT.move()
dT.move()
dT.motorStop()

print("\n forward all full...\n")
dT.setDistance(100)
dT.setSpeed(100)
dT.setHeading(0)
dT.setTargetHeading(0)
dT.move()
dT.move()
dT.motorStop()

print("\n left turn all full...\n")
dT.setDistance(100)
dT.setSpeed(100)
dT.setHeading(0)
dT.setTargetHeading(-50)
dT.move()
dT.move()
dT.motorStop()

print("\n right turn all full reverse...\n")
dT.setDistance(100)
dT.setSpeed(-100)
dT.setHeading(0)
dT.setTargetHeading(50)
dT.move()
dT.move()
dT.motorStop()

print("\n left turn all reverse half >180 ...\n")
dT.setDistance(100)
dT.setSpeed(-50)
dT.setHeading(0)
dT.setTargetHeading(200)
dT.move()
dT.move()
dT.motorStop()
