import MotorDriver

dT = MotorDriver.MotorDriver()
#dT.setDistance(100)
# dT.setSpeed(100)
# dT.setHeading(0)
# dT.setTargetHeading(100)
# dT.tmpSetDecision("right")
# dT.move()
# dT.move()
# dT.move()
# dT.move()
# dT.move()
# dT.move()
# dT.move()
# dT.move()
# dT.move()
# dT.move()
# dT.move()
# dT.move()
# dT.move()
# dT.motorStop()
dT.motorTest()